
title: IMPACT Lab
description: Intelligent Modulation, Power Architecture & Control Technologies
baseurl: ""
url: "https://your-username.github.io"
email: youremail@example.com
theme: minima
markdown: kramdown
